---
# play71--palo-alto-setup.yaml

- name: Play71 - Palo Alto Networks Device Setup
#  vars:
#    hosts: grouppaloalto
  # Usage: Pass a valid host or a group on the command line via the argument 'hosts'.
  hosts: "{{ hosts }}"
  tasks:
    ####
    - name: T01 - First Connect - admin/admin
      palo_provider:
        api_key: LUFRPT14MW5xOEo1R09KVlBZNnpnemh0VHRBOWl6TGM9bXcwM3JHUGVhRlNiY0dCR0srNERUQT09
#        api_key: {{ device_api_key }}
        ip_address: {{ ansible_host }}
      adminusername: admin
      adminpassword: admin
      register: out_first_conn
    - name: T01-out
      debug:
        var: out_first_conn.stdout_lines
    ####


