---
# play01--full-info.yaml

- name: Play01 - EC2 fresh instance - Gather Information Before Setup
#  vars:
#    hosts: groupmain
  # Usage: Pass a valid host or a group on the command line via the argument 'hosts'.
  hosts: "{{ hosts }}"
  tasks:
    ####
    - name: T01 - Date, Time -- date
      command: date
      register: out_date
    - name: T01-out
      debug:
        var: out_date.stdout_lines
    ####
    - name: T02 - Locate env (we need env for portable shebangs) -- which env
      command: which env
      register: out_which_env
    - name: T02-out
      debug:
        var: out_which_env.stdout_lines
    ####
    - name: T03 - Locate bash (we use bash for everything) -- which bash
      command: which bash
      register: out_which_bash
    - name: T03-out
      debug:
        var: out_which_bash.stdout_lines
    ####
    - name: T04 - System and Kernel Info -- uname -a
      command: uname -a
      register: out_uname
    - name: T04-out
      debug:
        var: out_uname.stdout_lines
    ####
    - name: T05 - Proc Version -- cat /proc/version
      command: cat /proc/version
      register: out_version
    - name: T05-out
      debug:
        var: out_version.stdout_lines
    ####
    - name: T06 - Process Table -- ps aux
      command: ps aux
      register: out_ps
    - name: T06-out
      debug:
        var: out_ps.stdout_lines
    ####
    - name: T07 - Memory Stats -- vmstat
      command: vmstat
      register: out_vmstat
    - name: T07-out
      debug:
        var: out_vmstat.stdout_lines
    ####
    - name: T08 - IO Stats -- iostat
      command: iostat
      register: out_iostat
    - name: T08-out
      debug:
        var: out_iostat.stdout_lines
    ####
    - name: T09 - PATH -- echo "$PATH"
      command: echo "$PATH"
      register: out_path
    - name: T09-out
      debug:
        var: out_path.stdout_lines
    ####
    - name: T10 - List Block Devices -- lsblk
      command: lsblk
      register: out_lsblk
    - name: T10-out
      debug:
        var: out_lsblk.stdout_lines
    ####
    - name: T11 - Disk Freespace -- df -h
      command: df -h
      register: out_df
    - name: T11-out
      debug:
        var: out_df.stdout_lines
    ####
    - name: T12 - List Filesystem Mount Points -- mount
      command: mount
      register: out_mount
    - name: T12-out
      debug:
        var: out_mount.stdout_lines
    ####
    - name: T13 - List All System Limits - (file descriptors, stack size, etc.) (VIA ansible.builtin.shell) -- ulimit -a
      ansible.builtin.shell:
        cmd: ulimit -a
      register: out_ulimit
    - name: T13-out
      debug:
        var: out_ulimit.stdout_lines
    ####
    - name: T14 - Environment Variables -- env
      command: env
      register: out_env
    - name: T14-out
      debug:
        var: out_env.stdout_lines
    ####

...

